version: "3.9"

services:
  backend:
    build: ./udatabackend
    container_name: udata-backend
    env_file:
      - .env        # Inject DATABASE_URL into container
    ports:
      - "8000:8000"

  frontend:
    build: ./udatafrontend
    container_name: udata-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend


